spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tcm_health_system?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: ${DB_PASSWORD:your_db_password}
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin123
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
  redis:
    host: localhost
    port: 6379
    password: ${REDIS_PASSWORD:your_redis_password}
    database: 1
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    com.hospital: info
    com.hospital.mapper: info
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'

oss:
  access-key-id: ${OSS_ACCESS_KEY_ID:your_access_key_id}
  access-key-secret: ${OSS_ACCESS_KEY_SECRET:your_access_key_secret}
  endpoint: oss-cn-beijing.aliyuncs.com
  bucket-name: ${OSS_BUCKET_NAME:your_bucket_name}
  avatar-path: avatar/
  url-protocol: https

auth:
  jwt:
    secret: ${JWT_SECRET:your_jwt_secret_key}
    expiration: 7200000

user:
  default-password: 123456

cors:
  allowed-origins: http://localhost:3000,http://127.0.0.1:3000

avatar:
  default-patient: https://api.dicebear.com/7.x/thumbs/svg?seed=patient
  default-doctor: https://api.dicebear.com/7.x/thumbs/svg?seed=doctor
  default-admin: https://api.dicebear.com/7.x/thumbs/svg?seed=admin

appointment:
  payment-timeout-minutes: 30

aliyun:
  area:
    api:
      host: https://areasel.market.alicloudapi.com
      path: /v1/area/search
      app-key: ${ALIYUN_AREA_APP_KEY:your_app_key}
      app-secret: ${ALIYUN_AREA_APP_SECRET:your_app_secret}
      app-code: ${ALIYUN_AREA_APP_CODE:your_app_code}
      cache-ttl-seconds: 604800
  deepseek:
    api-key: ${DEEPSEEK_API_KEY:your_deepseek_api_key}
    api-url: https://api.deepseek.com
    model: deepseek-chat
    max-tokens: 500
    temperature: 0.7
    cache-ttl-hours: 2

hospital:
  security:
    sensitive-key: ${HOSPITAL_SECURITY_KEY:your_security_key}

